services:
  app:
    image: docker.io/searxng/searxng:latest
    container_name: searxng-app
    hostname: search
    restart: always
    pull_policy: always
    environment:
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
      - REDIS_HOST=searxng-valkey
      - SEARXNG_BASE_URL=https://${BASE_HOST_NAME}
    ports:
      - '172.17.0.1:59089:8080'
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - './rootfs/config/searngx:/etc/searxng'
    depends_on:
      - valkey
    networks:
      - searxng

  valkey:
    image: docker.io/valkey/valkey:8-alpine
    container_name: searxng-valkey
    hostname: valkey
    restart: always
    pull_policy: always
    command: valkey-server --save 30 1 --loglevel warning
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    volumes:
      - './rootfs/db/valkey:/data'
    networks:
      - searxng

networks:
  searxng:
    name: searxng
    external: false
